### ISSUE TITLE
TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by sandoche** [iNeoO/vue-meeting-selector#19]
I copied pasted the "Fast exemple" and I got this error:
```
app.js:74403 Uncaught (in promise) TypeError: Super expression must either be null or a function
    at _inherits (app.js:74403:11)
    at app.js:75420:3
    at Module.fb15 (app.js:75488:2)
    at __nested_webpack_require_187__ (app.js:70087:30)
    at app.js:70151:18
    at Object../node_modules/vue-meeting-selector/dist/lib/vue-meeting-selector.common.js (app.js:70154:10)
    at __webpack_require__ (app.js:78998:33)
    at fn (app.js:79250:21)
    at Module../node_modules/babel-loader/lib/index.js??clonedRuleSet-5.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./resources/js/Pages/FlowBooking.vue?vue&type=script&lang=js (app.js:27153:78)
    at __webpack_require__ (app.js:78998:33)
```

I guess it's because I use Vue 3

**Comment by sandoche** [comment]
Issue linked to https://github.com/iNeoO/vue-meeting-selector/issues/14

**Comment by iNeoO** [comment]
Hi, yes, i didn t finish the portage on vue3

**Comment by sandoche** [comment]
Is there a "preview" branch that could be temporarly used?

**Comment by iNeoO** [comment]
no atm it'just local, i ported the component, but tested nothing. i will release a vue3 version of the component on a branch before the end of the week

**Comment by sandoche** [comment]
Amazin thanks!

**Comment by iNeoO** [comment]
Hi,

I made a release https://www.npmjs.com/package/vue-meeting-selector/v/2.0.0-beta-1 I tested on dev it works (maybe i missed some features, in that case tell me) Doc should bee the same (I didn't update it, migre it atm). there is a working exemple in src/Dev.vue anyway in ts

**Comment by sandoche** [comment]
Awesome thanks a lot. I'll give a try later today or tomorrow!

**Comment by sandoche** [comment]
Will do this later

**Comment by iNeoO** [comment]
i did it for a portage to alpine

```javascript
/**
 * @typedef {Object} MeetingSlot
 * @property {Date} date - Date of the meeting
 * any other props
 */

/**
 * @typedef {Object} Time
 * @property {number} hours - Hours
 * @property {number} minutes - Minutes
 */

/**
 * used to format a date, to compare with other date without time
 * @param {Date} date - Date to decompose
 * @return {String} YYYYMMDD
 */
function formatingDate(date) {
  const d = new Date(date);
  const day = d.getDate() < 10 ? `0${d.getDate()}` : d.getDate();
  const month = d.getMonth() + 1 < 10 ? `0${d.getMonth() + 1}` : d.getMonth() + 1;
  const year = d.getFullYear();
  return `${year}-${month}-${day}`;
}

/**
 * Function to random a number between min and max
 * @param {Number} min - A date
 * @param {Number} max - time of the date
 * @return {number}
  */
function randomNumber(min, max) {
  return Math.floor(Math.random() * (max - min) + min);
}

/**
 * Set a time to a date
 * @param {Date} date - A date
 * @param {Time} time - time of the date
 * @return {Date} date with the good time
  */
function setTime(date, time) {
  const d = new Date(date);
  d.setHours(time.hours);
  d.setMinutes(time.minutes);
  d.setSeconds(0);
  d.setMilliseconds(0);
  return d;
}

function roundToClosestTime(date, interval) {
  const d = new Date(date);
  const minutes = d.getMinutes();
  const minutesToAdd = minutes % interval;
  d.setMinutes(minutes + (interval - minutesToAdd));
  d.setSeconds(0);
  d.setMilliseconds(0);
  return d;
}

/**
 * Round a date with tz
 * @param {Date} date - date used to disable
 */
function roundDate(date) {
  const tz = -date.getTimezoneOffset();
  const time = {
    hours: Math.floor(tz / 60),
    minutes: tz % 60,
  };
  return setTime(date, time);
}

/**
 * Function to generate the first slot of the week used
 * @param {Date} date - date used to disable
 * @param {Number} interval - Interval between two meetings (minutes)
 * @param {Time} startTime - startTime of the meetings
 * @param {Time} endTime - endTime of the meetings
 * @param {number} randomSlotsToDelete - Number of slots to delete randomly
 * @return {MeetingSlot[]} - A list of meetings
 */
function generateSlots(start, end, interval, randomSlotsToDelete) {
  let startStamp = start.getTime();
  const endStamp = end.getTime();
  const slots = [];
  for (;startStamp <= endStamp; startStamp += interval * 60000) {
    const slot = {
      date: new Date(startStamp),
    };
    slots.push(slot);
  }
  for (let i = 0; i < randomSlotsToDelete; i += 1) {
    const indexToDelete = randomNumber(0, slots.length);
    slots.splice(indexToDelete, 1);
  }
  return slots;
}

/**
 * Function to generate the first slot of the week used
 * @param {Date} date - date used to disable
 * @param {Number} interval - Interval between two meetings (minutes)
 * @param {Time} startTime - startTime of the meetings
 * @param {Time} endTime - endTime of the meetings
 * @return {MeetingSlot} - A meetingSlot returned
 */
function generateFirstDate(date, interval, startTime, endTime) {
  let start;
  if (formatingDate(date) <= formatingDate(new Date())) {
    start = roundToClosestTime(date, interval);
    if (start.getTime() < setTime(date, startTime)) {
      start = setTime(date, startTime);
    }
  } else {
    start = setTime(date, startTime);
  }
  const end = setTime(date, endTime);
  const slots = generateSlots(start, end, interval);
  return {
    date: roundDate(date),
    slots,
  };
}

/**
 * Function applicated to the button previous to disable it
 * @param {Date} date - date used to disable
 * @param {Number} nbDays - number of days to generate
 * @param {Time} startTime - startTime of the meetings
 * @param {Time} endTime - endTime of the meetings
 * @param {Number} interval - Interval between two meetings (minutes)
 * @param {number} randomSlotsToDelete - Number of slots to delete randomly
 * @return {MeetingSlot[]} - list of slots
 */
function generateDays(date, nbDays, startTime, endTime, interval, randomSlotsToDelete = 0) {
  const days = [];
  days.push(generateFirstDate(date, interval, startTime, endTime));
  // Set to second Day
  const startingDay = new Date(date);
  for (let i = 1; i < nbDays; i += 1) {
    const slotsDate = new Date(startingDay.setDate(startingDay.getDate() + 1));
    /**
     * Use this to not display sunday and saturday
     * if (slotsDate.getDay() === 0 || slotsDate.getDay() === 6) {
     *   i -= 1;
     * } else {
     */
    const startDate = setTime(slotsDate, startTime);
    const endDate = setTime(slotsDate, endTime);
    const slots = generateSlots(
      startDate,
      endDate,
      interval,
      randomSlotsToDelete,
    );
    const meetingsDay = {
      date: roundDate(startingDay),
      slots,
    };
    days.push(meetingsDay);
    // }
  }
  return days;
}

export default generateDays;
```

**Comment by sandoche** [comment]
Amazing thanks! I'll give a try!

**Comment by sandoche** [comment]
I used your helper and added this in the code showed above:
```js
    getMeetings(date) {
      const start = {
        hours: 8,
        minutes: 0,
      };
      const end = {
        hours: 16,
        minutes: 0,
      };

      this.meetingsDays = generateDays(date, 5, start, end, 30);
    },
```

**Comment by sandoche** [comment]
I tried with the vue components and the composition API using your helper and I still get some errors.

Here is my code:
```js
<template>
  <div>
    <div id="app">
      <vue-meeting-selector
        ref="meetingSelector"
        v-model="meeting"
        class="meeting-selector"
        :date="date"
        :loading="false"
        :meetings-days="meetingsDays"
        @next-date="nextDate"
        @previous-date="previousDate"
      >
        <!-- <template
        #header="{ meetings }">
        <div>{{ meetings.date }}</div>
      </template>
      <template #button-up="{ isDisabled }">
        <button
          :disabled="isDisabled"
          @click="up">
          up</button>
      </template>
      <template
        #button-down="{ isDisabled }">
        <button
          :disabled="isDisabled"
          @click="down"
          >down</button>
      </template>
      <template
        #meeting="{ meeting }">
        <div>{{ meeting.date }}</div>
      </template> -->
      </vue-meeting-selector>
    </div>
  </div>
</template>

<script>
import { defineComponent, ref } from 'vue'
import VueMeetingSelector from 'vue-meeting-selector';
import slotsGenerator from '@/Helpers/slotsGenerator';

export default defineComponent({
  components: {
    VueMeetingSelector
  },
  setup() {
    const meeting = ref(null);
    const meetingsDays = ref([]);
    const nbDaysToDisplay = ref(5);
    const date = ref(new Date());
    const initMeetingsDays = () => {
      const start = {
        hours: 8,
        minutes: 0
      };
      const end = {
        hours: 16,
        minutes: 0
      };
      meetingsDays.value = slotsGenerator(
        new Date(),
        nbDaysToDisplay.value,
        start,
        end,
        30
      );

      console.log(meetingsDays.value)
    };
    initMeetingsDays();
    const meetingSelector = ref(null);
    const up = function () {
      meetingSelector.value.previousMeetings();
    };  
    const down = () => {
      meetingSelector.value.nextMeetings();
    };

    const nextDate = () => {
      const start = {
        hours: 8,
        minutes: 0
      };
      const end = {
        hours: 16,
        minutes: 0
      };
      const d = new Date(date.value);
      const newDate = new Date(d.setDate(d.getDate() + 7));
      date.value = newDate;
      meetingsDays.value = slotsGenerator(
        newDate,
        nbDaysToDisplay.value,
        start,
        end,
        30
      );
    };
    const previousDate = () => {
      const start = {
        hours: 8,
        minutes: 0
      };
      const end = {
        hours: 16,
        minutes: 0
      };
      const d = new Date(date.value);
      d.setDate(d.getDate() - 7);
      const formatingDate = (dateToFormat) => {
        const dateParsed = new Date(dateToFormat);
        const day = dateParsed.getDate() < 10 ? `0${dateParsed.getDate()}` : dateParsed.getDate();
        const month = dateParsed.getMonth() + 1 < 10 ? `0${dateParsed.getMonth() + 1}` : dateParsed.getMonth() + 1;
        const year = dateParsed.getFullYear();
        return `${year}-${month}-${day}`;
      };
    
      const newDate = formatingDate(new Date()) >= formatingDate(d)
        ? new Date()
        : new Date(d);
    
      date.value = newDate;
    
      meetingsDays.value = slotsGenerator(
        newDate,
        nbDaysToDisplay.value,
        start,
        end,
        30
      );
    };
    return {
      meeting,
      meetingsDays,
      date,
      meetingSelector,
      up,
      down,
      nextDate,
      previousDate
    };
  }
})
</script>
```
The error I get
```js
app.js:75322 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'date')
    at ReactiveEffect.fn (app.js:75322:53)
    at ReactiveEffect.run (app.js:11946:29)
    at ComputedRefImpl.get value [as value] (app.js:12868:39)
    at unref (app.js:12778:29)
    at Object.get (app.js:12781:37)
    at Object.get (app.js:19086:34)
    at Proxy.MeetingDisplayvue_type_template_id_f65b001c_scoped_true_bindings_render (app.js:75223:84)
    at renderComponentRoot (app.js:13578:44)
    at ReactiveEffect.componentUpdateFn [as fn] (app.js:17426:57)
    at ReactiveEffect.run (app.js:11946:29)
```

**Comment by iNeoO** [comment]
i updated and publich a beta-2, should be fine now. I added the `slotsGenerator.js` in `/helper`, you can know `import slotsGenerator from 'vue-meting-selector/src/helpers/slotsGenerator.js'`

**Comment by sandoche** [comment]
I'll give a try!

**Comment by sandoche** [comment]
It seems to work !!! awesome thanks a lot!

**Comment by sandoche** [comment]
Everything worked perfectly for my usecase, feel free to close the issue.
