### ISSUE TITLE
Uncaught TypeError: Object(...) is not a function  error on console 

### ISSUE THREAD

**Issue by AhmadAlaswadDev** [iNeoO/vue-meeting-selector#29]
hi 
im facing this error on console while adding simple example to the view 

app.js:762 Uncaught TypeError: Object(...) is not a function
    at Module.fb15 (MeetingDisplay.vue?4fdd:5:1)
    at __nested_webpack_require_2552__ (bootstrap?5c00:19:1)
    at module.exports.00ee (bootstrap?5c00:83:1)
    at eval (bootstrap?5c00:83:1)
    at Object../node_modules/vue-meeting-selector/dist/lib/vue-meeting-selector.common.js (chunk-vendors.js:4155:1)
    at __webpack_require__ (app.js:759:33)
    at fn (app.js:1010:21)
    at eval (index.js??clonedRuleSet-40[0].rules[0].use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/views/Home.vue?vue&type=script&lang=js&:4:78)
    at Module../node_modules/babel-loader/lib/index.js??clonedRuleSet-40[0].rules[0].use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/views/Home.vue?vue&type=script&lang=js& (app.js:347:1)
    at __webpack_require__ (app.js:759:33)

My dependncies are:
  "dependencies": {
    "axios": "^0.27.2",
    "babel-eslint": "^10.1.0",
    "bootstrap": "^5.1.3",
    "bootstrap-vue": "^2.22.0",
    "core-js": "^3.22.6",
    "crypto-js": "^4.1.1",
    "express": "^4.18.1",
    "lodash": "^4.17.21",
    "path": "^0.12.7",
    "serve-static": "^1.15.0",
    "socket.io-client": "^4.5.1",
    "vue": "^2.6.14",
    "vue-cookies": "^1.8.1",
    "vue-meeting-selector": "^2.0.0-beta-3",
    "vue-router": "^3.5.1",
    "vue-webrtc": "^3.0.1",
    "vuex": "^3.6.2"
  },

**Comment by AhmadAlaswadDev** [comment]
its working now ...

i noticed the version of vue-meeting-selector while im getting dependencies to the post 

just downgrade the version to 
 "vue-meeting-selector": "1.1.3",

and it will work perfectly

**Comment by AhmadAlaswadDev** [comment]
is there a way to disable up and down buttons and display full column  of slots @iNeoO  ?

**Comment by iNeoO** [comment]
Hi,

You can set empty span in slot to manage that and set calendarOptions.limit at the max number of slots per column

**Comment by nxmndr** [comment]
Hello,

Error is still there.

**Comment by iNeoO** [comment]
HI, i'm working on a rebuild with vite i will try to make a release this weekend

**Comment by nxmndr** [comment]
Awesome. Will it work with the usual webpack configs (like Laravel's) ?

Do you have a Patreon or equivalent ?

**Comment by iNeoO** [comment]
I made the release, i didn t hard test it, tell me if you have any pb

No, il don't have this.
