### ISSUE TITLE
nuxt3 - document is not defined

### ISSUE THREAD

**Issue by a-zog** [iNeoO/vue-meeting-selector#34]
Hi,

Just followed [this demo](https://codesandbox.io/s/vue3-meeting-selector-hiloic?file=/src/App.vue) in order to install VueMeetingSelector (^2.0.0-beta-3) on **nuxt3 (RC9)** and I got this error:

```
[nuxt] [request error] [unhandled] [500] document is not defined
  at addStyle (./node_modules/vue-meeting-selector/dist/lib/vue-meeting-selector.common.js:1070:22)
  at addStylesToDom (./node_modules/vue-meeting-selector/dist/lib/vue-meeting-selector.common.js:1054:20)
  at addStylesClient (./node_modules/vue-meeting-selector/dist/lib/vue-meeting-selector.common.js:1008:3)
  at Object.c7 (./node_modules/vue-meeting-selector/dist/lib/vue-meeting-selector.common.js:3176:14)
  at __webpack_require__ (./node_modules/vue-meeting-selector/dist/lib/vue-meeting-selector.common.js:21:30)
  at Module.fb15 (./node_modules/vue-meeting-selector/dist/lib/vue-meeting-selector.common.js:4238:18)
  at __webpack_require__ (./node_modules/vue-meeting-selector/dist/lib/vue-meeting-selector.common.js:21:30)
  at ./node_modules/vue-meeting-selector/dist/lib/vue-meeting-selector.common.js:85:18
  at Object.<anonymous> (./node_modules/vue-meeting-selector/dist/lib/vue-meeting-selector.common.js:88:10)
  at Module._compile (node:internal/modules/cjs/loader:1105:14)
```

Didn't even work even after putting ```<client-only>``` around.

Would you please suggest a proper way of solving this?

Thanks,
Keep up the great work

**Comment by iNeoO** [comment]
Hi, tried with clientonly, and it s work for me https://codesandbox.io/s/jovial-solomon-ls6oqk?file=/app.vue
